>P1;ptm0.787_r3_default
Structure: ptm0.787_r3_default: 1:A : 100:A ::::
MDADVISFEASR-GDLVVLDAIHDARFETEAGPGVYDIHSPRIPSEKEIEDRIYEILDKIDVKKVWINPD
CGLKTRGNDETWPSLEHLVAAAKAVRARLDK*
>P1;Assignment5_73f88_unrelaxed_rank_1_model_3
Structure: Assignment5_73f88_unrelaxed_rank_1_model_3: 1:A : 100:A ::::
MDADVISFEASRGD-LVVLDAIHDARFETEAGPGVYDIHSPRIPSEKEIEDRIYEILDKIDVKKVWINPD
CGLKTRGNDETWPSLEHLVAAAKAVRARLDK*

